name: Build and Update
on:
  push:
    branches:
      - test

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      
      - name: Build the binary
        run: |
          mkdir -p ./bin
          go build -o ./bin/publisher ./publisher/main.go
      
      - name: Run the binary to update file
        run: ./bin/publisher .
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Auto update file via GitHub Actions" || exit 0
          git push
